name: HackAction

on:
  pull_request:
    types: [labeled]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every 5 minutes is minimun ofr action schduler
    - cron: "*/5 * * * *"
    # run at 9 am every day
    # - chron: '0 9 * * *'

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: actionBot

        # uses: ./Hackathon-ActionBot/
        uses: nsoto92/Hackathon-ActionBot@master
        with:
          active: true
          channel: team_hackathon
          slack-auth: ${{secrets.slackbot_token}}
          repo-token: ${{secrets.GITHUB_TOKEN}}
