name: HackAction

on:
  pull_request:
    types: [labeled]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'    

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: actionBot

        # uses: ./Hackathon-ActionBot/
        uses: nsoto92/Hackathon-ActionBot@master
        with:
          channel: team_hackathon
          slackAuth: ${{secrets.slackbot_token}}
          repo-token: ${{secrets.GITHUB_TOKEN}}
